version: "3.9"

services:
  backend:
    build: ./backend
    container_name: healthhub-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: healthhub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000
